server:
  port: 8888

spring:
  application:
    name: server

  redis:
    host: redis
    timeout: 60
    port: 6379
    database: 0
    password:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/sf2cs?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      show-sql: true
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: consul
      port: 8500
  servlet:
    multipart:
      max-file-size: 10MB
application:
  face-recognize:
    core-pool-size: 5
    max-pool-size: 10
    point: MODEL_5
    device: AUTO
    threshold: 0.75f
    wait-second: 2


