spring:
  application:
    name: management
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://mysql:3306/sf2cs?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  redis:
    host: redis
    timeout: 60
    port: 6379
    database: 0
    password:
  cloud:
    consul:
      discovery:
        service-name: ${spring.application.name}
      host: consul
      port: 8500


application:
  task-pool:
    common:
      core-pool-size: 10
      max-pool-size: 20
      keep-alive-seconds: 60
